POST http://localhost:3001/products
Content-Type: application/json

{
    "title":"test",
    "completed": true
}

###
GET http://localhost:3001/products

###
PUT http://localhost:3001/products/2
Content-Type: application/json

{
    "completed": false,
    "title": "sport"
}